[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --cov=src --cov-report=term-missing
env =
    TESTING=True
    JWT_SECRET_KEY=test_secret_key_for_jwt
    DATABASE_URL=sqlite:///./test.db
